### ISSUE TITLE
3 arrow in right color

### ISSUE THREAD

**Issue by Extremelyd1** [Extremelyd1/Robot-race#2]

**Comment by Dacaspex** [comment]
From the course manual:
> The axes have length 1 meter, are aligned with the X, Y , and Z axes, and consist of a block with a cone at the end to show the direction. Show the position of the origin with a yellow sphere. Use red, green, and blue as colors for the X, Y , and Z axes, respectively.

* The lengths of the vertices are 1
* At the end there is a cone
* The arrows are coloured

**Comment by Extremelyd1** [comment]
Arrows use lines instead of solid object
